### ISSUE TITLE
Finish head() and reveal() methods

### ISSUE THREAD

**Issue by prithajnath** [prithajnath/kalamari#1]
The `Tree` class has two methods, `head()` and `reveal()` which are supposed to help visualize the underlying JSON structure. `head()` should only print the first few levels, depending on how deep the tree is, and `reveal()` should print the entire tree structure. You don't have to implement the search yourself because the `__iter__` method already lets you traverse the tree level by level. Also, feel free to suggest better names for these methods!

**Comment by dylanfw** [comment]
I'll give this a shot. Let me know if you have any suggestions or recommendations for this beyond your comment here. I see the methods have some more information commented out in them currently to work from.

**Comment by joviij** [comment]
Can I try this?

**Comment by prithajnath** [comment]
@joviij sure thing!

**Comment by joviij** [comment]
@prithajnath Should we rename the head() function to something like peek()? head() seems a bit misleading. What do you think?

**Comment by prithajnath** [comment]
Sounds good to me!

**Comment by joviij** [comment]
@prithajnath Also for both the reveal() and the peek() methods, it's a fair bit easier to print out the tree in a vertical manner

root
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--child
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--grandchild
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--grandchild2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--child2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--grandchild
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--great-grandchild


and so on. I have a semi-working horizontal approach but its kind of complicated to wrap around. What's your opinion on the approach we should take?

**Comment by prithajnath** [comment]
@joviij either way is fine
